name = "sapa-tomo-bot"
compatibility_date = "2024-01-01"

[[vars]]
key = "GOOGLE_SHEETS_CREDENTIALS"
value = "be631db09be0e8bb8617dac84a6aad0d5ad67d20"

[[vars]]
key = "SPREADSHEET_ID"
value = "108579236797130129265"

[[vars]]
key = "ADMIN_NUMBERS"
value = "62812xxxxxxx,62813xxxxxxx"
